### ISSUE TITLE
Questions need to be asked in an order

### ISSUE THREAD

**Issue by gangadevib** [CS4244/Where2Go#1]
Leisure after visit preference

**Comment by Dauth** [comment]
have added 
(desired (visitPreference "Leisure"))
so that the question is generated after leisure is selected

But still if you need it to be called immediately, try to retract and assert previous questions except the current one

**Comment by gangadevib** [comment]
As long as leisure is fired right after visitpreference, then this shld be fine.

**Comment by Dauth** [comment]
currently if on reset and run, eg there are 5 questions generated. If visit pref is qn4 and leisure is selected. It will generate the leisure question. But it will be be qn6 and qn 5 have to be asked. Salience doesn't help here.

**Comment by gangadevib** [comment]
Okay. I ran the app and saw it, it is similar to the the type of activities. I think it doesn't affect the question flow that much.
